### PR TITLE
Erd schema branch

### PR DESCRIPTION
**Pull request by jeeva1429**
Created ER Diagram for the project which is having 5 entities
1. User -> Attributes:  UserId, Role, UserName, Password
2. Prescriptions ->Attributes: PrescriptionId, PrescriptionDate, TotalCost, UserId
3. PrescriptionDetails ->Attributes : PrescriptionId, PrescriptionDetails, MedicineId, Quantity, Dosage
4. Inventory -> Attributes : MedicineId, QuantityInStock
5. Medicine -> Attributes : MedicineId, MedicineName, Manufacturer, Price, ExpiryDate

I have attached a video on explaining the ERD and Schema in Loom.
https://www.loom.com/share/5e5670abd5f74e588d7b72e36782db56?sid=1a2f6a95-4111-4ae9-9254-5a93ff0e1f59

### CODE REVIEW

**Review by th3c0d3br34ker — COMMENTED** [review]
thanks @jeeva1429 for your submissions. it is sufficient for a self-viva

Please add the relationship between 
1. `PrescriptionDetails` and `Medicines`
2. `Medicines` and `Inventory`

Please update the diagram and let me know.

**Comment by jeeva1429** [comment]
Hi Jainam, sorry for the delayed response,
can you give me your tribe id so that i can text you and ask about my doubt

**Comment by th3c0d3br34ker** [comment]
please reach out [@jainam.d](https://tribe.kalvium.community/u/jainam.d) or book a slot for viva, link is available in the wiki.

**Comment by jeeva1429** [comment]
I had commited the changes you had suggested Jainam

**Review by th3c0d3br34ker — APPROVED** [review]
thanks @jeeva1429 for reverting, consider mentioning the changes in the comment as well. 

for now please go ahead with your project.

**Pull request merged**
